### ISSUE TITLE
Priority - Irregular shading

### ISSUE THREAD

**Issue by mpaluta** [tyu0912/MIDS_W207_facial_recognition#11]
Some images are much darker/lighter. This may or may not be a good thing.

Possible adjustment: find method to lighten or darken closer to average pixel density across all images.

Possible concern: can we do this on the test data too? Otherwise we will lose robustness to dark/light images.

**Comment by tyu0912** [comment]
https://en.wikipedia.org/wiki/Normalization_(image_processing)
