### ISSUE TITLE
How to handle NA values

### ISSUE THREAD

**Issue by mpaluta** [tyu0912/MIDS_W207_facial_recognition#3]
Filling NA with 0 is probably not ideal in end state, but not sure how to handle yet.

Possible ideas:
 - have algorithm guess that the feature should be NA. Assign fixed cost to incorrect assignment of NA (0 cost if assignment is correct).

**Comment by mbulkow** [comment]
custom loss function ignores cost of na values

**Comment by alexdauenhauer** [comment]
After the meeting we decided to move forward with custom loss function which handles NAs
